feat: component searchBar
WildCodeSchool-2024-09/toulouse-p2-cinewild pull request #7
Opened 2024-11-15 16:24 UTC by radwan-osman

2024-11-16 10:52 UTC, cedricrighi requested changes

2024-11-16 10:52 UTC, cedricrighi commented on client/src/components/FilmSearchBar.tsx
> +const apiKey = "a6624acbe4190aa63573701aac791391";
Pense à mettre la valeur de la variable apiKey dans un fichier .env, c'est mieux pour éviter que tout le monde puisse l'obtenir

2024-11-16 10:52 UTC, cedricrighi commented on client/src/main.tsx
> +  </StrictMode>,
Attention à la présence d'espaces dans le fichier, je ne sais pas si ça vient du fait que t'as mis axios, pose la question à Arthur si jamais

2024-11-16 15:12 UTC, cedricrighi approved these changes

2024-11-18 08:33 UTC, ArthurHtbk approved these changes

2024-11-18 09:26 UTC, merged