S1 us01/minicard
WildCodeSchool-2024-09/toulouse-p2-cinewild pull request #8
Opened 2024-11-18 13:18 UTC by TSMB54

2024-11-18 15:02 UTC, cedricrighi approved these changes

2024-11-18 15:18 UTC, ArthurHtbk requested changes
- Noms de variable et de fichiers => anglais
- Noms plus clairs => ex : `isYearOpen` au lieu de `isOpena`
- Code plus scalable => toujours préférer mapper de la donnée plutôt que de l'écrire en dur

2024-11-19 15:03 UTC, radwan-osman approved these changes

2024-11-19 15:21 UTC, ArthurHtbk approved these changes

2024-11-19 15:21 UTC, merged